require:
 - rubocop-rails
 - rubocop-performance

AllCops:
  TargetRubyVersion: 3.0.0
  Exclude:
    - "tmp/**/*"
    - "node_modules/**/*"
    - "db/schema.rb"
    - "db/seeds.rb"
    - "db/data/*"
    - "db/migrate/*"
    - "bin/rails"
    - "bin/rake"
    - "bin/spring"
    - "db/test_seeds.rb"

Rails:
  Enabled: true

# Ready for Ruby 3, almost :)
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/FormatStringToken:
  Enabled: false

Layout/LineLength:
  Max: 125

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 100
  Exclude:
    - "spec/**/*"

Metrics/ModuleLength:
  Max: 100
  Exclude:
    - "spec/**/*"
    - "app/helpers/constants.rb"

Metrics/MethodLength:
  Max: 25
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Max: 25
  Exclude:
    - "spec/**/*"

Style/Documentation:
  Exclude:
    - "db/**/*"

Style/RaiseArgs:
  EnforcedStyle: compact

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
